name: Mavericks
favicon: null
layout_spectrum: 0.5990617657080293
typography_spectrum: 0.27004132024012506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8920812492724508
  lightness: 0.1790548386052251
  saturation: 0.4561916529200971
  rhythmicContrast: 0.9162014133762568
purpose: []
